//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public string Subject { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ResolvedAt { get; set; }
        public int Type_Id { get; set; }
        public int Status_Id { get; set; }
        public int Customer_Id { get; set; }
        public int ServiceType_Id { get; set; }
        public int Priority_Id { get; set; }
        public int Creator_Id { get; set; }
        public int Asignee_Id { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual ServiceType ServiceType { get; set; }
        public virtual Status Status { get; set; }
        public virtual TicketType TicketType { get; set; }
        public virtual User Creator { get; set; }
        public virtual User Asignee { get; set; }
    }
}
